version: "20.10.21"
services:
  postgres:
    image: postgres
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=picoles"
    ports:
      - 5441:5432
