from model.aditivo_nutritivo import AditivoNutritivo
from model.conservante import Conservante
from model.ingrediente import Ingrediente
from model.lote import Lote
from model.nota_fiscal import NotaFiscal
from model.picole import Picole
from model.revendedor import Revendedor
from model.sabor import Sabor
from model.tipo_embalagem import TipoEmbalagem
from model.tipo_picole import TipoPicole
